### ISSUE TITLE
Need Perl Packages

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/starforge#16]
It sure would be nice to have gross statistics on which packages take the longest to compile/install...since that's a bit of a UX issue, if we knew which ones needed pre-compilation, we could do that.

**Comment by bgruening** [comment]
My take on this is that if it is easy enough to compile a package and it takes under 1h we should do it via source. docker-build and the `depot` are awesome but still it is an additional layer of complexity.

**Comment by hexylena** [comment]
Under 1h! You are very patient!

**Comment by bgruening** [comment]
:) I'm a dreamer, I expect that we only install perl once for every Galaxy instance.

**Comment by hexylena** [comment]
Yep! And that's a fair assumption.

However when testing packages...every time I set up a temporary Galaxy, it means 30 minutes of doing something else while I wait for perl/R/etc

**Comment by bgruening** [comment]
@erasche go for it, this was just my opinion. We need to draw some line, otherwise we can try to compile everything. I usually avoid such problem with a special docker flavor. Maybe the [genome-annotation flavor](https://github.com/bgruening/docker-galaxy-genome-annotation) has perl already installed?

**Comment by hexylena** [comment]
Agreed, a line would be nice. So would @jmchilton implementing brew.

+1 for GAF having perl preinstalled.

**Comment by nsoranzo** [comment]
We use Conda packages for this now.
