### ISSUE TITLE
Should wheels/build/wheels.yml live in Galaxy?

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#43]
As pointed out by @chambm, updating this file is really a Galaxy-specific task, not Starforge. Should it live in the Galaxy repo instead?

One downside: The Jenkins job that checks for changes to wheels.yml and attempts to build the wheels would need to run on Galaxy instead, and would run for every Galaxy PR despite only being applicable to a very small percentage of them.

**Comment by hexylena** [comment]
http://stackoverflow.com/questions/5243593/how-to-trigger-a-build-only-if-changes-happen-on-particular-set-of-files

**Comment by martenson** [comment]
@erasche the problem is not the build detection but whether to pollute the 'continuous integration' space in github for every Galaxy PR with report that only few PRs will have relevancy.

Basically we need a way to have PR builder run builds but not report back to GitHub unless we somehow tell it to. I did google for a bit but did not find a good solution.

**Comment by hexylena** [comment]
When a galaxy build is triggered, trigger a downstream build for starforge stuff. In that build, add this plugin/check to determine if that build should run. Won't pollute upstream at all. :)

**Comment by hexylena** [comment]
As for reporting back on PRs... that's a bit tougher. I don't know of _any_ way to do that

**Comment by natefoo** [comment]
This is now done in [starforge-recipes](https://github.com/galaxyproject/starforge-recipes)
